apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-sa
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jwt-sa
    spec:
      containers:
      - name: jwt
        image: mickyxd/jwtsa:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: SECRET
          value: "grupo1"
        - name: PAYLOAD
          value: "sa"
        - name: MYSQL_HOST
          value: "34.136.151.30"
        - name: MYSQL_PORT
          value: "3302"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "p@Ssw0Rd1234"
        - name: MYSQL_DB
          value: "SA"