apiVersion: apps/v1
kind: Deployment
metadata:
  name: administrador-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administrador-sa
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: administrador-sa
    spec:
      containers:
      - name: administrador
        image: mickyxd/administradorsa:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: db_port
          value: "3306"
        - name: db_user
          value: "admin"
        - name: db_pass
          value: "S0ftwareavanzad0"
        - name: db_host
          value: "sa.cz3pvq6x9ohw.us-west-2.rds.amazonaws.com"
        - name: db_name
          value: "SA"
        - name: SECRET
          value: "grupo1"