apiVersion: v1
kind: Service
metadata:
  name: administrador-service
spec:
  #type: ClusterIP
  type: LoadBalancer
  ports:
    - port: 80 #Externo
      targetPort: 80 #Interno
  selector:
    app: administrador-sa