apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jwt-sa
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jwt-sa
    spec:
      containers:
      - name: jwt
        image: mickyxd/jwtsa:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: SECRET
          value: "grupo1"
        - name: PAYLOAD
          value: "sa"
        - name: MYSQL_HOST
          value: "sa.cz3pvq6x9ohw.us-west-2.rds.amazonaws.com"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "S0ftwareavanzad0"
        - name: MYSQL_DB
          value: "SA"