apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificacion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificacion-sa
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notificacion-sa
    spec:
      containers:
      - name: notificacion
        image: mickyxd/notificacionsa:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: MYSQL_HOST
          value: "sa.cz3pvq6x9ohw.us-west-2.rds.amazonaws.com"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "Softwareavanzad0"
        - name: MYSQL_DB
          value: "SA"
        - name: EMAIL
          value: "handc.gt@gmail.com"
        - name: EMAIL_PASS
          value: "HacheYCe.GeTe"
