apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportes-sa
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reportes-sa
    spec:
      containers:
      - name: reportes
        image: mickyxd/reportessa:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: SECRET
          value: "grupo1"
        - name: db_port
          value: "3306"
        - name: db_user
          value: "admin"
        - name: db_pass
          value: "Softwareavanzad0"
        - name: db_host
          value: "sa.cz3pvq6x9ohw.us-west-2.rds.amazonaws.com"
        - name: db_name
          value: "SA"
        - name: SECRET
          value: "grupo1"
        - name: MYSQL_HOST
          value: "sa.cz3pvq6x9ohw.us-west-2.rds.amazonaws.com"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "admin"
        - name: MYSQL_PASSWORD
          value: "Softwareavanzad0"
        - name: MYSQL_DB
          value: "SA"
